spring.application.name=Noblesse

spring.datasource.url=jdbc:sqlite:inventaire.db
spring.datasource.driver-class-name=org.sqlite.JDBC


spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
#server.servlet.context-path=/noblesseApi




server.port=8080
debug=true
